drop user CONVOCATORIA cascade;
create user CONVOCATORIA 
identified by CONVOCATORIA default tablespace users quota 10M on users;
grant all privileges to CONVOCATORIA;





-- -----------------------------------------------------
-- Table `CONVOCATORIA`.`PAIS`
-- -----------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CONVOCATORIA.PAIS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/ 

CREATE TABLE CONVOCATORIA.PAIS (
  PAIS_IDPAIS NUMBER(10) NOT NULL,
  PAIS_NOMBRE VARCHAR2(45) NOT NULL,
  PAIS_ESTADO NUMBER(3) DEFAULT 1 NOT NULL,
  PRIMARY KEY (PAIS_IDPAIS))
;

-- Generate ID using sequence and trigger
CREATE SEQUENCE CONVOCATORIA.PAIS_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER CONVOCATORIA.PAIS_seq_tr
 BEFORE INSERT ON CONVOCATORIA.PAIS FOR EACH ROW
 WHEN (NEW.PAIS_IDPAIS IS NULL)
BEGIN
 SELECT CONVOCATORIA.PAIS_seq.NEXTVAL INTO :NEW.PAIS_IDPAIS FROM DUAL;
END;
/


-- -----------------------------------------------------
-- Table `CONVOCATORIA`.`DEPARTAMENTO`
-- -----------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CONVOCATORIA.DEPARTAMENTO';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/ 

CREATE TABLE CONVOCATORIA.DEPARTAMENTO (
  DPTO_IDDEPARTAMENTO NUMBER(10) NOT NULL,
  DPTO_NOMBRE VARCHAR2(45) NOT NULL,
  DPTO_ESTADO NUMBER(3) DEFAULT 1 NOT NULL,
  PAIS_IDPAIS NUMBER(10) NOT NULL,
  PRIMARY KEY (DPTO_IDDEPARTAMENTO, PAIS_IDPAIS),
  CONSTRAINT fk_DEPARTAMENTO_PAIS1
    FOREIGN KEY (PAIS_IDPAIS)
    REFERENCES CONVOCATORIA.PAIS (PAIS_IDPAIS)
   )
;

-- Generate ID using sequence and trigger
CREATE SEQUENCE CONVOCATORIA.DEPARTAMENTO_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER CONVOCATORIA.DEPARTAMENTO_seq_tr
 BEFORE INSERT ON CONVOCATORIA.DEPARTAMENTO FOR EACH ROW
 WHEN (NEW.DPTO_IDDEPARTAMENTO IS NULL)
BEGIN
 SELECT CONVOCATORIA.DEPARTAMENTO_seq.NEXTVAL INTO :NEW.DPTO_IDDEPARTAMENTO FROM DUAL;
END;
/

CREATE INDEX fk_DEPARTAMENTO_PAIS1_idx ON CONVOCATORIA.DEPARTAMENTO (PAIS_IDPAIS ASC);


-- -----------------------------------------------------
-- Table `CONVOCATORIA`.`CIUDAD`
-- -----------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CONVOCATORIA.CIUDAD';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/ 

CREATE TABLE CONVOCATORIA.CIUDAD (
  CIDD_IDCIUDAD NUMBER(10) NOT NULL,
  CIDD_NOMBRE VARCHAR2(45) NOT NULL,
  CIDD_ESTADO NUMBER(3) DEFAULT 1 NOT NULL,
  DPTO_IDDEPARTAMENTO NUMBER(10) NOT NULL,
  PRIMARY KEY (CIDD_IDCIUDAD, DPTO_IDDEPARTAMENTO),
  CONSTRAINT fk_CIUDAD_DEPARTAMENTO
    FOREIGN KEY (DPTO_IDDEPARTAMENTO)
    REFERENCES CONVOCATORIA.DEPARTAMENTO (DPTO_IDDEPARTAMENTO)
   )
;

CREATE INDEX fk_CIUDAD_DEPARTAMENTO_idx ON CONVOCATORIA.CIUDAD (DPTO_IDDEPARTAMENTO ASC);


-- -----------------------------------------------------
-- Table `CONVOCATORIA`.`TIPO_DOCUMENTO`
-- -----------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CONVOCATORIA.TIPO_DOCUMENTO';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/ 

CREATE TABLE CONVOCATORIA.TIPO_DOCUMENTO (
  TPDC_IDTIPODOCUMENTO NUMBER(10) NOT NULL,
  TPDC_NOMBRE VARCHAR2(45) NOT NULL,
  TPDC_ESTADO NUMBER(3) DEFAULT 1 NOT NULL,
  PRIMARY KEY (TPDC_IDTIPODOCUMENTO))
;

-- Generate ID using sequence and trigger
CREATE SEQUENCE CONVOCATORIA.TIPO_DOCUMENTO_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER CONVOCATORIA.TIPO_DOCUMENTO_seq_tr
 BEFORE INSERT ON CONVOCATORIA.TIPO_DOCUMENTO FOR EACH ROW
 WHEN (NEW.TPDC_IDTIPODOCUMENTO IS NULL)
BEGIN
 SELECT CONVOCATORIA.TIPO_DOCUMENTO_seq.NEXTVAL INTO :NEW.TPDC_IDTIPODOCUMENTO FROM DUAL;
END;
/


-- -----------------------------------------------------
-- Table `CONVOCATORIA`.`DOCENTE`
-- -----------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CONVOCATORIA.DOCENTE';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/ 

CREATE TABLE CONVOCATORIA.DOCENTE (
  DCNT_IDDOCENTE NUMBER(10) NOT NULL,
  DCNT_APELLIDO1 VARCHAR2(45) NOT NULL,
  DCNT_APELLIDO2 VARCHAR2(45) NULL,
  DCNT_NOMBRES VARCHAR2(45) NOT NULL,
  DCNT_NUM_LB_MILITAR VARCHAR2(45) NULL,
  DCNT_FECHA_NAC DATE NOT NULL,
  DCNT_DIRECCION_RESI VARCHAR2(45) NOT NULL,
  DCNT_NUM_TEL_FIJO VARCHAR2(45) NULL,
  DCNT_NUM_TEL_MOVIL VARCHAR2(45) NULL,
  DCNT_NUM_DOC VARCHAR2(20) NOT NULL,
  DCNT_EMAIL VARCHAR2(45) NOT NULL,
  DCNT_FECHA_REGISTR TIMESTAMP(0) DEFAULT SYSTIMESTAMP NOT NULL,
  CIDD_IDCIUDAD_ACTUAL NUMBER(10) NOT NULL,
  PAIS_IDPAIS_NACIONALIDAD NUMBER(10) NOT NULL,
  TPDC_IDTIPODOCUMENTO NUMBER(10) NOT NULL,
  CIDD_IDCIUDAD_EXP_DOC NUMBER(10) NOT NULL ,
  DCNT_ACTIVO NUMBER(3) DEFAULT 0 NOT NULL,
  PRIMARY KEY (DCNT_IDDOCENTE, CIDD_IDCIUDAD_ACTUAL, PAIS_IDPAIS_NACIONALIDAD, TPDC_IDTIPODOCUMENTO, CIDD_IDCIUDAD_EXP_DOC),
  CONSTRAINT fk_DOCENTE_CIUDAD1
    FOREIGN KEY (CIDD_IDCIUDAD_ACTUAL)
    REFERENCES CONVOCATORIA.CIUDAD (CIDD_IDCIUDAD)
   ,
  CONSTRAINT fk_DOCENTE_PAIS1
    FOREIGN KEY (PAIS_IDPAIS_NACIONALIDAD)
    REFERENCES CONVOCATORIA.PAIS (PAIS_IDPAIS)
   ,
  CONSTRAINT fk_DOCENTE_TIPODOCUMENTO1
    FOREIGN KEY (TPDC_IDTIPODOCUMENTO)
    REFERENCES CONVOCATORIA.TIPO_DOCUMENTO (TPDC_IDTIPODOCUMENTO)
   ,
  CONSTRAINT fk_DOCENTE_CIUDAD2
    FOREIGN KEY (CIDD_IDCIUDAD_EXP_DOC)
    REFERENCES CONVOCATORIA.CIUDAD (CIDD_IDCIUDAD)
   )
;

-- Generate ID using sequence and trigger
CREATE SEQUENCE CONVOCATORIA.DOCENTE_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER CONVOCATORIA.DOCENTE_seq_tr
 BEFORE INSERT ON CONVOCATORIA.DOCENTE FOR EACH ROW
 WHEN (NEW.DCNT_IDDOCENTE IS NULL)
BEGIN
 SELECT CONVOCATORIA.DOCENTE_seq.NEXTVAL INTO :NEW.DCNT_IDDOCENTE FROM DUAL;
END;
/

CREATE INDEX fk_DOCENTE_CIUDAD1_idx ON CONVOCATORIA.DOCENTE (CIDD_IDCIUDAD_ACTUAL ASC);

CREATE INDEX fk_DOCENTE_PAIS1_idx ON CONVOCATORIA.DOCENTE (PAIS_IDPAIS_NACIONALIDAD ASC);

CREATE INDEX fk_DOCENTE_TIPODOCUMENTO1_idx ON CONVOCATORIA.DOCENTE (TPDC_IDTIPODOCUMENTO ASC);

CREATE INDEX fk_DOCENTE_CIUDAD2_idx ON CONVOCATORIA.DOCENTE (CIDD_IDCIUDAD_EXP_DOC ASC);


-- -----------------------------------------------------
-- Table `CONVOCATORIA`.`INSCRIPCION`
-- -----------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CONVOCATORIA.INSCRIPCION';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/ 

CREATE TABLE CONVOCATORIA.INSCRIPCION (
  INCN_IDINSCRIPCION NUMBER(10) NOT NULL,
  INCN_MANIFESTACION VARCHAR2(500) NULL ,
  INCN_DESDE TIMESTAMP(0) DEFAULT SYSTIMESTAMP NOT NULL,
  INCN_HASTA TIMESTAMP(0) NULL,
  INCN_LUGAR VARCHAR2(45) NULL,
  INCN_DESCRIPCION VARCHAR2(100) NULL,
  INCN_ATENCION1 TIMESTAMP(3) NULL,
  INCN_ATENCION2 TIMESTAMP(3) NULL,
  INCN_JURADOS VARCHAR2(500) NULL,
  PRIMARY KEY (INCN_IDINSCRIPCION))
;

-- Generate ID using sequence and trigger
CREATE SEQUENCE CONVOCATORIA.INSCRIPCION_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER CONVOCATORIA.INSCRIPCION_seq_tr
 BEFORE INSERT ON CONVOCATORIA.INSCRIPCION FOR EACH ROW
 WHEN (NEW.INCN_IDINSCRIPCION IS NULL)
BEGIN
 SELECT CONVOCATORIA.INSCRIPCION_seq.NEXTVAL INTO :NEW.INCN_IDINSCRIPCION FROM DUAL;
END;
/


-- -----------------------------------------------------
-- Table `CONVOCATORIA`.`ARCHIVO`
-- -----------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CONVOCATORIA.ARCHIVO';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/ 

CREATE TABLE CONVOCATORIA.ARCHIVO (
  ARCV_IDARCHIVO NUMBER(10) NOT NULL,
  ARCV_DESCRIPCION VARCHAR2(45) NOT NULL,
  ARCV_DIRNAME VARCHAR2(150) NOT NULL,
  PRIMARY KEY (ARCV_IDARCHIVO))
;


-- -----------------------------------------------------
-- Table `CONVOCATORIA`.`TIPO_PROFESION`
-- -----------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CONVOCATORIA.TIPO_PROFESION';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/ 

CREATE TABLE CONVOCATORIA.TIPO_PROFESION (
  TPPR_IDTIPOPROFESION NUMBER(10) NOT NULL,
  TPPR_NOMBRE VARCHAR2(45) NULL ,
  PRIMARY KEY (TPPR_IDTIPOPROFESION))
;


-- -----------------------------------------------------
-- Table `CONVOCATORIA`.`PROFESION`
-- -----------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CONVOCATORIA.PROFESION';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/ 

CREATE TABLE CONVOCATORIA.PROFESION (
  PRFN_IDPROFESION NUMBER(10) NOT NULL,
  PRFN_TITULO VARCHAR2(100) NOT NULL,
  TPPR_IDTIPOPROFESION NUMBER(10) NOT NULL,
  PRIMARY KEY (PRFN_IDPROFESION, TPPR_IDTIPOPROFESION),
  CONSTRAINT fk_PROFESION_TIPOPROFESION1
    FOREIGN KEY (TPPR_IDTIPOPROFESION)
    REFERENCES CONVOCATORIA.TIPO_PROFESION (TPPR_IDTIPOPROFESION)
   )
;

-- Generate ID using sequence and trigger
CREATE SEQUENCE CONVOCATORIA.PROFESION_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER CONVOCATORIA.PROFESION_seq_tr
 BEFORE INSERT ON CONVOCATORIA.PROFESION FOR EACH ROW
 WHEN (NEW.PRFN_IDPROFESION IS NULL)
BEGIN
 SELECT CONVOCATORIA.PROFESION_seq.NEXTVAL INTO :NEW.PRFN_IDPROFESION FROM DUAL;
END;
/

CREATE INDEX fk_PROFESION_TIPOPROFESION1_idx ON CONVOCATORIA.PROFESION (TPPR_IDTIPOPROFESION ASC);


-- -----------------------------------------------------
-- Table `CONVOCATORIA`.`PERFIL`
-- -----------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CONVOCATORIA.PERFIL';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/ 

CREATE TABLE CONVOCATORIA.PERFIL (
  PRFL_IDPERFIL NUMBER(10) NOT NULL,
  PRFN_IDPROFESION NUMBER(10) NOT NULL,
  DCNT_IDDOCENTE NUMBER(10) NOT NULL,
  PRIMARY KEY (PRFL_IDPERFIL, PRFN_IDPROFESION, DCNT_IDDOCENTE),
  CONSTRAINT fk_PERFIL_PROFESION1
    FOREIGN KEY (PRFN_IDPROFESION)
    REFERENCES CONVOCATORIA.PROFESION (PRFN_IDPROFESION)
   ,
  CONSTRAINT fk_PERFIL_DOCENTE1
    FOREIGN KEY (DCNT_IDDOCENTE)
    REFERENCES CONVOCATORIA.DOCENTE (DCNT_IDDOCENTE)
   )
;

-- Generate ID using sequence and trigger
CREATE SEQUENCE CONVOCATORIA.PERFIL_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER CONVOCATORIA.PERFIL_seq_tr
 BEFORE INSERT ON CONVOCATORIA.PERFIL FOR EACH ROW
 WHEN (NEW.PRFL_IDPERFIL IS NULL)
BEGIN
 SELECT CONVOCATORIA.PERFIL_seq.NEXTVAL INTO :NEW.PRFL_IDPERFIL FROM DUAL;
END;
/

CREATE INDEX fk_PERFIL_PROFESION1_idx ON CONVOCATORIA.PERFIL (PRFN_IDPROFESION ASC);

CREATE INDEX fk_PERFIL_DOCENTE1_idx ON CONVOCATORIA.PERFIL (DCNT_IDDOCENTE ASC);


-- -----------------------------------------------------
-- Table `CONVOCATORIA`.`SOPORTE`
-- -----------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CONVOCATORIA.SOPORTE';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/ 

CREATE TABLE CONVOCATORIA.SOPORTE (
  SPTE_FECHAREGISTRO TIMESTAMP(0) DEFAULT NULL NOT NULL,
  ARCV_IDARCHIVO NUMBER(10) NOT NULL,
  DCNT_IDDOCENTE NUMBER(10) NOT NULL,
  PRIMARY KEY (ARCV_IDARCHIVO, DCNT_IDDOCENTE),
  CONSTRAINT fk_SOPORTE_ARCHIVO1
    FOREIGN KEY (ARCV_IDARCHIVO)
    REFERENCES CONVOCATORIA.ARCHIVO (ARCV_IDARCHIVO)
   ,
  CONSTRAINT fk_SOPORTE_DOCENTE1
    FOREIGN KEY (DCNT_IDDOCENTE)
    REFERENCES CONVOCATORIA.DOCENTE (DCNT_IDDOCENTE)
   )
;

CREATE INDEX fk_SOPORTE_DOCENTE1_idx ON CONVOCATORIA.SOPORTE (DCNT_IDDOCENTE ASC);


-- -----------------------------------------------------
-- Table `CONVOCATORIA`.`PERSONAL`
-- -----------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CONVOCATORIA.PERSONAL';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/ 

CREATE TABLE CONVOCATORIA.PERSONAL (
  PRSL_IDPERSONAL NUMBER(10) NOT NULL,
  PRSL_PUNTAJE_TOTAL NUMBER(10) DEFAULT 0 NOT NULL,
  PRSL_PUNTAJE_MAX NUMBER(10) DEFAULT 0 NOT NULL,
  PRIMARY KEY (PRSL_IDPERSONAL))
;


-- -----------------------------------------------------
-- Table `CONVOCATORIA`.`INVESTIGACION`
-- -----------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CONVOCATORIA.INVESTIGACION';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/ 

CREATE TABLE CONVOCATORIA.INVESTIGACION (
  INVN_IDINVESTIGACION NUMBER(10) NOT NULL,
  INVN_PUNTAJE_TOTAL NUMBER(10) DEFAULT 0 NOT NULL,
  INVN_PUNTAJE_MAX NUMBER(10) DEFAULT 0 NOT NULL,
  PRIMARY KEY (INVN_IDINVESTIGACION))
;

-- Generate ID using sequence and trigger
CREATE SEQUENCE CONVOCATORIA.INVESTIGACION_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER CONVOCATORIA.INVESTIGACION_seq_tr
 BEFORE INSERT ON CONVOCATORIA.INVESTIGACION FOR EACH ROW
 WHEN (NEW.INVN_IDINVESTIGACION IS NULL)
BEGIN
 SELECT CONVOCATORIA.INVESTIGACION_seq.NEXTVAL INTO :NEW.INVN_IDINVESTIGACION FROM DUAL;
END;
/


-- -----------------------------------------------------
-- Table `CONVOCATORIA`.`DOCENCIA`
-- -----------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CONVOCATORIA.DOCENCIA';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/ 

CREATE TABLE CONVOCATORIA.DOCENCIA (
  DCCA_IDDOCENCIA NUMBER(10) NOT NULL,
  DCCA_PUNTAJE_TOTAL NUMBER(10) NULL,
  DCCA_PUNTAJE_MAX NUMBER(10) NULL,
  PRIMARY KEY (DCCA_IDDOCENCIA))
;


-- -----------------------------------------------------
-- Table `CONVOCATORIA`.`PROFESIONAL`
-- -----------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CONVOCATORIA.PROFESIONAL';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/ 

CREATE TABLE CONVOCATORIA.PROFESIONAL (
  PNAL_IDPROFESIONAL NUMBER(10) NOT NULL,
  PNAL_PUNTAJE_TOTAL NUMBER(10) NULL,
  PNAL_PUNTAJE_MAX NUMBER(10) NULL,
  PRIMARY KEY (PNAL_IDPROFESIONAL))
;


-- -----------------------------------------------------
-- Table `CONVOCATORIA`.`PRODUCCION`
-- -----------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CONVOCATORIA.PRODUCCION';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/ 

CREATE TABLE CONVOCATORIA.PRODUCCION (
  PRCN_IDPRODUCCION NUMBER(10) NOT NULL,
  PRCN_PUNTAJE_TOTAL NUMBER(10) DEFAULT 0 NULL,
  PRCN_PUNTAJE_MAX NUMBER(10) DEFAULT 0 NULL,
  PRIMARY KEY (PRCN_IDPRODUCCION))
;


-- -----------------------------------------------------
-- Table `CONVOCATORIA`.`CONOCIMIENTO`
-- -----------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CONVOCATORIA.CONOCIMIENTO';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/ 

CREATE TABLE CONVOCATORIA.CONOCIMIENTO (
  CNTO_IDCONOC_DETALLE NUMBER(10) NOT NULL,
  CNTO_DOMINIO_CONCEP NUMBER(10) DEFAULT 0 NOT NULL,
  CNTO_PROFUNDIDAD NUMBER(10) DEFAULT 0 NOT NULL,
  CNTO_ARGUMENTACION NUMBER(10) DEFAULT 0 NOT NULL,
  CNTO_SEC_LOGICA NUMBER(10) DEFAULT 0 NOT NULL,
  CNTO_ESTRA_DIDACTICA NUMBER(10) DEFAULT 0 NOT NULL,
  CMDT_COMUNICACION NUMBER(10) DEFAULT 0 NOT NULL,
  CNTO_TOTAL NUMBER(10) DEFAULT 0 NOT NULL,
  CNTO_TOTAL_MAX NUMBER(10) DEFAULT 0 NOT NULL,
  PRIMARY KEY (CNTO_IDCONOC_DETALLE))
;

-- Generate ID using sequence and trigger
CREATE SEQUENCE CONVOCATORIA.CONOCIMIENTO_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER CONVOCATORIA.CONOCIMIENTO_seq_tr
 BEFORE INSERT ON CONVOCATORIA.CONOCIMIENTO FOR EACH ROW
 WHEN (NEW.CNTO_IDCONOC_DETALLE IS NULL)
BEGIN
 SELECT CONVOCATORIA.CONOCIMIENTO_seq.NEXTVAL INTO :NEW.CNTO_IDCONOC_DETALLE FROM DUAL;
END;
/


-- -----------------------------------------------------
-- Table `CONVOCATORIA`.`COMPETENCIA`
-- -----------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CONVOCATORIA.COMPETENCIA';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/ 

CREATE TABLE CONVOCATORIA.COMPETENCIA (
  CMPC_IDCOMPETENCIA NUMBER(10) NOT NULL,
  CMPC_PUNTAJE_TOTAL VARCHAR2(45) NULL,
  CMPC_MAX_PUNTOS NUMBER(10) DEFAULT 30 NOT NULL,
  PRSL_IDPERSONAL NUMBER(10) NOT NULL,
  INVN_IDINVESTIGACION NUMBER(10) NOT NULL,
  DCCA_IDDOCENCIA NUMBER(10) NOT NULL,
  PNAL_IDPROFESIONAL NUMBER(10) NOT NULL,
  PRCN_IDPRODUCCION NUMBER(10) NOT NULL,
  DCNT_IDDOCENTE NUMBER(10) NOT NULL,
  CNTO_IDCONOC_DETALLE NUMBER(10) NOT NULL,
  PRIMARY KEY (CMPC_IDCOMPETENCIA, PRSL_IDPERSONAL, INVN_IDINVESTIGACION, DCCA_IDDOCENCIA, PNAL_IDPROFESIONAL, PRCN_IDPRODUCCION, DCNT_IDDOCENTE, CNTO_IDCONOC_DETALLE),
  CONSTRAINT fk_COMPETENCIA_PERSONAL1
    FOREIGN KEY (PRSL_IDPERSONAL)
    REFERENCES CONVOCATORIA.PERSONAL (PRSL_IDPERSONAL)
   ,
  CONSTRAINT fk_COMPETENCIA_INVESTIGACION1
    FOREIGN KEY (INVN_IDINVESTIGACION)
    REFERENCES CONVOCATORIA.INVESTIGACION (INVN_IDINVESTIGACION)
   ,
  CONSTRAINT fk_COMPETENCIA_DOCENCIA1
    FOREIGN KEY (DCCA_IDDOCENCIA)
    REFERENCES CONVOCATORIA.DOCENCIA (DCCA_IDDOCENCIA)
   ,
  CONSTRAINT fk_COMPETENCIA_PROFESIONAL1
    FOREIGN KEY (PNAL_IDPROFESIONAL)
    REFERENCES CONVOCATORIA.PROFESIONAL (PNAL_IDPROFESIONAL)
   ,
  CONSTRAINT fk_COMPETENCIA_PRODUCCION1
    FOREIGN KEY (PRCN_IDPRODUCCION)
    REFERENCES CONVOCATORIA.PRODUCCION (PRCN_IDPRODUCCION)
   ,
  CONSTRAINT fk_COMPETENCIA_DOCENTE1
    FOREIGN KEY (DCNT_IDDOCENTE)
    REFERENCES CONVOCATORIA.DOCENTE (DCNT_IDDOCENTE)
   ,
  CONSTRAINT fk_COMPETENCIA_CONOCIMIENTO1
    FOREIGN KEY (CNTO_IDCONOC_DETALLE)
    REFERENCES CONVOCATORIA.CONOCIMIENTO (CNTO_IDCONOC_DETALLE)
   )
;

-- Generate ID using sequence and trigger
CREATE SEQUENCE CONVOCATORIA.COMPETENCIA_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER CONVOCATORIA.COMPETENCIA_seq_tr
 BEFORE INSERT ON CONVOCATORIA.COMPETENCIA FOR EACH ROW
 WHEN (NEW.CMPC_IDCOMPETENCIA IS NULL)
BEGIN
 SELECT CONVOCATORIA.COMPETENCIA_seq.NEXTVAL INTO :NEW.CMPC_IDCOMPETENCIA FROM DUAL;
END;
/

CREATE INDEX fk_COMPETENCIA_PERSONAL1_idx ON CONVOCATORIA.COMPETENCIA (PRSL_IDPERSONAL ASC);

CREATE INDEX fk_COMPETENCIA_INVESTIGACION1_idx ON CONVOCATORIA.COMPETENCIA (INVN_IDINVESTIGACION ASC);

CREATE INDEX fk_COMPETENCIA_DOCENCIA1_idx ON CONVOCATORIA.COMPETENCIA (DCCA_IDDOCENCIA ASC);

CREATE INDEX fk_COMPETENCIA_PROFESIONAL1_idx ON CONVOCATORIA.COMPETENCIA (PNAL_IDPROFESIONAL ASC);

CREATE INDEX fk_COMPETENCIA_PRODUCCION1_idx ON CONVOCATORIA.COMPETENCIA (PRCN_IDPRODUCCION ASC);

CREATE INDEX fk_COMPETENCIA_DOCENTE1_idx ON CONVOCATORIA.COMPETENCIA (DCNT_IDDOCENTE ASC);

CREATE INDEX fk_COMPETENCIA_CONOCIMIENTO1_idx ON CONVOCATORIA.COMPETENCIA (CNTO_IDCONOC_DETALLE ASC);


-- -----------------------------------------------------
-- Table `CONVOCATORIA`.`PERSONAL_DETALLE`
-- -----------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CONVOCATORIA.PERSONAL_DETALLE';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/ 

CREATE TABLE CONVOCATORIA.PERSONAL_DETALLE (
  TPPR_IDTIPOPROFESION NUMBER(10) NOT NULL,
  PRDT_UNIVERSIDAD VARCHAR2(45) NOT NULL,
  PRDT_GRADO DATE NOT NULL,
  PRDT_PUNTAJE NUMBER(10) DEFAULT 0 NOT NULL,
  PRDT_PUNTAJE_MAX NUMBER(10) NOT NULL,
  PERSONAL_PRSL_IDPERSONAL NUMBER(10) NOT NULL,
  PRIMARY KEY (TPPR_IDTIPOPROFESION, PERSONAL_PRSL_IDPERSONAL),
  CONSTRAINT fk_COMPETENCIA_PERSONAL_TIPO_PROFESION1
    FOREIGN KEY (TPPR_IDTIPOPROFESION)
    REFERENCES CONVOCATORIA.TIPO_PROFESION (TPPR_IDTIPOPROFESION)
   ,
  CONSTRAINT fk_PERSONAL_DETALLE_PERSONAL1
    FOREIGN KEY (PERSONAL_PRSL_IDPERSONAL)
    REFERENCES CONVOCATORIA.PERSONAL (PRSL_IDPERSONAL)
   )
;

CREATE INDEX fk_PERSONAL_DETALLE_PERSONAL1_idx ON CONVOCATORIA.PERSONAL_DETALLE (PERSONAL_PRSL_IDPERSONAL ASC);


-- -----------------------------------------------------
-- Table `CONVOCATORIA`.`INVESTIGACION_DETALLE`
-- -----------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CONVOCATORIA.INVESTIGACION_DETALLE';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/ 

CREATE TABLE CONVOCATORIA.INVESTIGACION_DETALLE (
  INVD_IDINVESTIGACION_DETALLE NUMBER(10) NOT NULL,
  INVD_FINANCIADORA VARCHAR2(70) NULL,
  INVD_FECHA_INICIO DATE NOT NULL,
  INVD_FECHA_FIN DATE NOT NULL,
  INVD_PUNTAJE NUMBER(10) DEFAULT 0 NOT NULL,
  INVN_IDINVESTIGACION NUMBER(10) NOT NULL,
  PRIMARY KEY (INVD_IDINVESTIGACION_DETALLE, INVN_IDINVESTIGACION),
  CONSTRAINT fk_INVESTIGACION_DETALLE_INVESTIGACION1
    FOREIGN KEY (INVN_IDINVESTIGACION)
    REFERENCES CONVOCATORIA.INVESTIGACION (INVN_IDINVESTIGACION)
   )
;

CREATE INDEX fk_INVESTIGACION_DETALLE_INVESTIGACION1_idx ON CONVOCATORIA.INVESTIGACION_DETALLE (INVN_IDINVESTIGACION ASC);


-- -----------------------------------------------------
-- Table `CONVOCATORIA`.`DOCENCIA_DETALLE`
-- -----------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CONVOCATORIA.DOCENCIA_DETALLE';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/ 

CREATE TABLE CONVOCATORIA.DOCENCIA_DETALLE (
  DCDT_IDDOCENCIA_DETALLE NUMBER(10) NOT NULL,
  DCDT_INSTITUCION VARCHAR2(45) NOT NULL,
  DCDT_AREA_TRABAJO VARCHAR2(45) NOT NULL,
  DCDT_CARGO VARCHAR2(45) NOT NULL,
  DCDT_INICIO DATE NULL,
  DCDT_FIN DATE NULL,
  DCDT_PUNTAJE NUMBER(10) NULL,
  DCCA_IDDOCENCIA NUMBER(10) NOT NULL,
  PRIMARY KEY (DCDT_IDDOCENCIA_DETALLE, DCCA_IDDOCENCIA),
  CONSTRAINT fk_DOCENCIA_DETALLE_DOCENCIA1
    FOREIGN KEY (DCCA_IDDOCENCIA)
    REFERENCES CONVOCATORIA.DOCENCIA (DCCA_IDDOCENCIA)
   )
;

-- Generate ID using sequence and trigger
CREATE SEQUENCE CONVOCATORIA.DOCENCIA_DETALLE_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER CONVOCATORIA.DOCENCIA_DETALLE_seq_tr
 BEFORE INSERT ON CONVOCATORIA.DOCENCIA_DETALLE FOR EACH ROW
 WHEN (NEW.DCDT_IDDOCENCIA_DETALLE IS NULL)
BEGIN
 SELECT CONVOCATORIA.DOCENCIA_DETALLE_seq.NEXTVAL INTO :NEW.DCDT_IDDOCENCIA_DETALLE FROM DUAL;
END;
/

CREATE INDEX fk_DOCENCIA_DETALLE_DOCENCIA1_idx ON CONVOCATORIA.DOCENCIA_DETALLE (DCCA_IDDOCENCIA ASC);


-- -----------------------------------------------------
-- Table `CONVOCATORIA`.`PROFESIONAL_DETALLE`
-- -----------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CONVOCATORIA.PROFESIONAL_DETALLE';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/ 

CREATE TABLE CONVOCATORIA.PROFESIONAL_DETALLE (
  PFDT_IDPROFESIONAL_DETALLE NUMBER(10) NOT NULL,
  PFDT_INSTITUCION VARCHAR2(45) NOT NULL,
  PFDT_AREA_TRABAJO VARCHAR2(45) NOT NULL,
  PFDT_CARGO VARCHAR2(45) NOT NULL,
  PFDT_FIN DATE NOT NULL,
  PFDT_INICIO DATE NOT NULL,
  PFDT_PUNTAJE NUMBER(10) DEFAULT 0 NULL,
  PNAL_IDPROFESIONAL NUMBER(10) NOT NULL,
  PRIMARY KEY (PFDT_IDPROFESIONAL_DETALLE, PNAL_IDPROFESIONAL),
  CONSTRAINT fk_PROFESIONAL_DETALLE_PROFESIONAL1
    FOREIGN KEY (PNAL_IDPROFESIONAL)
    REFERENCES CONVOCATORIA.PROFESIONAL (PNAL_IDPROFESIONAL)
   )
;

CREATE INDEX fk_PROFESIONAL_DETALLE_PROFESIONAL1_idx ON CONVOCATORIA.PROFESIONAL_DETALLE (PNAL_IDPROFESIONAL ASC);


-- -----------------------------------------------------
-- Table `CONVOCATORIA`.`PRODUCCION_DETALLE`
-- -----------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CONVOCATORIA.PRODUCCION_DETALLE';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/ 

CREATE TABLE CONVOCATORIA.PRODUCCION_DETALLE (
  PNDT_IDPRODUCCION NUMBER(10) NOT NULL,
  PNDT_NOMBRE_PRODUCTO VARCHAR2(100) NOT NULL,
  PNDT_TIPO_PRODUCTO VARCHAR2(45) NOT NULL,
  PNDT_IDENTIFICADOR_CERT VARCHAR2(45) NULL ,
  PNDT_VOLUMEN VARCHAR2(45) NULL,
  PNDT_FECHA_EDICION DATE NULL,
  PNDT_PUNTAJE NUMBER(10) NULL,
  PRCN_IDPRODUCCION NUMBER(10) NOT NULL,
  PRIMARY KEY (PNDT_IDPRODUCCION, PRCN_IDPRODUCCION),
  CONSTRAINT fk_PRODUCCION_DETALLE_PRODUCCION1
    FOREIGN KEY (PRCN_IDPRODUCCION)
    REFERENCES CONVOCATORIA.PRODUCCION (PRCN_IDPRODUCCION)
   )
;

-- Generate ID using sequence and trigger
CREATE SEQUENCE CONVOCATORIA.PRODUCCION_DETALLE_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER CONVOCATORIA.PRODUCCION_DETALLE_seq_tr
 BEFORE INSERT ON CONVOCATORIA.PRODUCCION_DETALLE FOR EACH ROW
 WHEN (NEW.PNDT_IDPRODUCCION IS NULL)
BEGIN
 SELECT CONVOCATORIA.PRODUCCION_DETALLE_seq.NEXTVAL INTO :NEW.PNDT_IDPRODUCCION FROM DUAL;
END;
/

CREATE INDEX fk_PRODUCCION_DETALLE_PRODUCCION1_idx ON CONVOCATORIA.PRODUCCION_DETALLE (PRCN_IDPRODUCCION ASC);


-- -----------------------------------------------------
-- Table `CONVOCATORIA`.`INSCRITOS`
-- -----------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CONVOCATORIA.INSCRITOS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/ 

CREATE TABLE CONVOCATORIA.INSCRITOS (
  ISNC_IDINSCRITOS NUMBER(10) NOT NULL,
  DCNT_IDDOCENTE NUMBER(10) NOT NULL,
  ISNC_FECHA_INS TIMESTAMP(0) DEFAULT SYSTIMESTAMP NOT NULL,
  INCN_IDINSCRIPCION NUMBER(10) NOT NULL,
  ISNC_OBSERVACION VARCHAR2(150) DEFAULT '' NULL,
  PRIMARY KEY (ISNC_IDINSCRITOS, DCNT_IDDOCENTE, INCN_IDINSCRIPCION),
  CONSTRAINT fk_INSCRITOS_DOCENTE1
    FOREIGN KEY (DCNT_IDDOCENTE)
    REFERENCES CONVOCATORIA.DOCENTE (DCNT_IDDOCENTE)
   ,
  CONSTRAINT fk_INSCRITOS_INSCRIPCION1
    FOREIGN KEY (INCN_IDINSCRIPCION)
    REFERENCES CONVOCATORIA.INSCRIPCION (INCN_IDINSCRIPCION)
   )
;

-- Generate ID using sequence and trigger
CREATE SEQUENCE CONVOCATORIA.INSCRITOS_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER CONVOCATORIA.INSCRITOS_seq_tr
 BEFORE INSERT ON CONVOCATORIA.INSCRITOS FOR EACH ROW
 WHEN (NEW.ISNC_IDINSCRITOS IS NULL)
BEGIN
 SELECT CONVOCATORIA.INSCRITOS_seq.NEXTVAL INTO :NEW.ISNC_IDINSCRITOS FROM DUAL;
END;
/

CREATE INDEX fk_INSCRITOS_DOCENTE1_idx ON CONVOCATORIA.INSCRITOS (DCNT_IDDOCENTE ASC);

CREATE INDEX fk_INSCRITOS_INSCRIPCION1_idx ON CONVOCATORIA.INSCRITOS (INCN_IDINSCRIPCION ASC);


/* SET SQL_MODE=@OLD_SQL_MODE; */
/* SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS; */
/* SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS; */
