create or replace PROCEDURE PR_SELECT_PAIS (CR_RESULT OUT SYS_REFCURSOR) AS
BEGIN
OPEN CR_RESULT FOR
    SELECT * FROM SEMILLEROS_UDLA.PAIS;
END PR_SELECT_PAIS;
/

create or replace PROCEDURE PR_INSERT_PAIS
(
    PAIS_IDPAIS NUMBER, PAIS_NOMBRE VARCHAR2, PAIS_ESTADO tinyint
)
AS BEGIN
    INSERT INTO SEMILLEROS_UDLA.PAIS (PAIS_IDPAIS, PAIS_NOMBRE, PAIS_ESTADO)
    VALUES (PAIS_IDPAIS, PAIS_NOMBRE, PAIS_ESTADO);
END PR_INSERT_PAIS;
/

create or replace PROCEDURE PR_UPDATE_PAIS
(
    PAIS_IDPAIS NUMBER, PAIS_NOMBRE VARCHAR2, PAIS_ESTADO tinyint
)
AS BEGIN
    UPDATE SEMILLEROS_UDLA.PAIS O 
    SET O.PAIS_NOMBRE = PAIS_NOMBRE, O.PAIS_ESTADO = PAIS_ESTADO WHERE O.PAIS_IDPAIS = PAIS_IDPAIS;
END PR_UPDATE_PAIS;
/

create or replace PROCEDURE PR_SELECT_DEPARTAMENTO (CR_RESULT OUT SYS_REFCURSOR) AS
BEGIN
OPEN CR_RESULT FOR
    SELECT * FROM SEMILLEROS_UDLA.DEPARTAMENTO;
END PR_SELECT_DEPARTAMENTO;
/

create or replace PROCEDURE PR_INSERT_DEPARTAMENTO
(
    DPTO_IDDEPARTAMENTO NUMBER, DPTO_NOMBRE VARCHAR2, DPTO_ESTADO tinyint, PAIS_IDPAIS NUMBER, INDEX `fk_departamento_pais1_idx`
)
AS BEGIN
    INSERT INTO SEMILLEROS_UDLA.DEPARTAMENTO (DPTO_IDDEPARTAMENTO, DPTO_NOMBRE, DPTO_ESTADO, PAIS_IDPAIS, INDEX)
    VALUES (DPTO_IDDEPARTAMENTO, DPTO_NOMBRE, DPTO_ESTADO, PAIS_IDPAIS, INDEX);
END PR_INSERT_DEPARTAMENTO;
/

create or replace PROCEDURE PR_UPDATE_DEPARTAMENTO
(
    DPTO_IDDEPARTAMENTO NUMBER, DPTO_NOMBRE VARCHAR2, DPTO_ESTADO tinyint, PAIS_IDPAIS NUMBER, INDEX `fk_departamento_pais1_idx`
)
AS BEGIN
    UPDATE SEMILLEROS_UDLA.DEPARTAMENTO O 
    SET O.DPTO_NOMBRE = DPTO_NOMBRE, O.DPTO_ESTADO = DPTO_ESTADO, O.PAIS_IDPAIS = PAIS_IDPAIS, O.INDEX = INDEX WHERE O.DPTO_IDDEPARTAMENTO = DPTO_IDDEPARTAMENTO;
END PR_UPDATE_DEPARTAMENTO;
/

create or replace PROCEDURE PR_SELECT_CIUDAD (CR_RESULT OUT SYS_REFCURSOR) AS
BEGIN
OPEN CR_RESULT FOR
    SELECT * FROM SEMILLEROS_UDLA.CIUDAD;
END PR_SELECT_CIUDAD;
/

create or replace PROCEDURE PR_INSERT_CIUDAD
(
    CIDD_IDCIUDAD NUMBER, CIDD_NOMBRE VARCHAR2, CIDD_ESTADO tinyint, DPTO_IDDEPARTAMENTO NUMBER, INDEX `fk_ciudad_departamento_idx`
)
AS BEGIN
    INSERT INTO SEMILLEROS_UDLA.CIUDAD (CIDD_IDCIUDAD, CIDD_NOMBRE, CIDD_ESTADO, DPTO_IDDEPARTAMENTO, INDEX)
    VALUES (CIDD_IDCIUDAD, CIDD_NOMBRE, CIDD_ESTADO, DPTO_IDDEPARTAMENTO, INDEX);
END PR_INSERT_CIUDAD;
/

create or replace PROCEDURE PR_UPDATE_CIUDAD
(
    CIDD_IDCIUDAD NUMBER, CIDD_NOMBRE VARCHAR2, CIDD_ESTADO tinyint, DPTO_IDDEPARTAMENTO NUMBER, INDEX `fk_ciudad_departamento_idx`
)
AS BEGIN
    UPDATE SEMILLEROS_UDLA.CIUDAD O 
    SET O.CIDD_NOMBRE = CIDD_NOMBRE, O.CIDD_ESTADO = CIDD_ESTADO, O.DPTO_IDDEPARTAMENTO = DPTO_IDDEPARTAMENTO, O.INDEX = INDEX WHERE O.CIDD_IDCIUDAD = CIDD_IDCIUDAD;
END PR_UPDATE_CIUDAD;
/

create or replace PROCEDURE PR_SELECT_TIPO_DOCUMENTO (CR_RESULT OUT SYS_REFCURSOR) AS
BEGIN
OPEN CR_RESULT FOR
    SELECT * FROM SEMILLEROS_UDLA.TIPO_DOCUMENTO;
END PR_SELECT_TIPO_DOCUMENTO;
/

create or replace PROCEDURE PR_INSERT_TIPO_DOCUMENTO
(
    TPDC_IDTIPODOCUMENTO NUMBER, TPDC_NOMBRE VARCHAR2, TPDC_ESTADO tinyint
)
AS BEGIN
    INSERT INTO SEMILLEROS_UDLA.TIPO_DOCUMENTO (TPDC_IDTIPODOCUMENTO, TPDC_NOMBRE, TPDC_ESTADO)
    VALUES (TPDC_IDTIPODOCUMENTO, TPDC_NOMBRE, TPDC_ESTADO);
END PR_INSERT_TIPO_DOCUMENTO;
/

create or replace PROCEDURE PR_UPDATE_TIPO_DOCUMENTO
(
    TPDC_IDTIPODOCUMENTO NUMBER, TPDC_NOMBRE VARCHAR2, TPDC_ESTADO tinyint
)
AS BEGIN
    UPDATE SEMILLEROS_UDLA.TIPO_DOCUMENTO O 
    SET O.TPDC_NOMBRE = TPDC_NOMBRE, O.TPDC_ESTADO = TPDC_ESTADO WHERE O.TPDC_IDTIPODOCUMENTO = TPDC_IDTIPODOCUMENTO;
END PR_UPDATE_TIPO_DOCUMENTO;
/

create or replace PROCEDURE PR_SELECT_DOCENTE (CR_RESULT OUT SYS_REFCURSOR) AS
BEGIN
OPEN CR_RESULT FOR
    SELECT * FROM SEMILLEROS_UDLA.DOCENTE;
END PR_SELECT_DOCENTE;
/

create or replace PROCEDURE PR_INSERT_DOCENTE
(
    DCNT_IDDOCENTE NUMBER, DCNT_APELLIDO1 VARCHAR2, DCNT_APELLIDO2 VARCHAR2, DCNT_NOMBRES VARCHAR2, DCNT_NUM_LB_MILITAR VARCHAR2, DCNT_FECHA_NAC DATE, DCNT_DIRECCION_RESI VARCHAR2, DCNT_NUM_TEL_FIJO VARCHAR2, DCNT_NUM_TEL_MOVIL VARCHAR2, DCNT_EMAIL VARCHAR2, DCNT_FECHA_REGISTR DATE, CIDD_IDCIUDAD_ACTUAL NUMBER, PAIS_IDPAIS_NACIONALIDAD NUMBER, TPDC_IDTIPODOCUMENTO NUMBER, CIDD_IDCIUDAD_EXP_DOC NUMBER, INDEX `fk_docente_ciudad1_idx`, INDEX `fk_docente_pais1_idx`, INDEX `fk_docente_tipodocumento1_idx`, INDEX `fk_docente_ciudad2_idx`
)
AS BEGIN
    INSERT INTO SEMILLEROS_UDLA.DOCENTE (DCNT_IDDOCENTE, DCNT_APELLIDO1, DCNT_APELLIDO2, DCNT_NOMBRES, DCNT_NUM_LB_MILITAR, DCNT_FECHA_NAC, DCNT_DIRECCION_RESI, DCNT_NUM_TEL_FIJO, DCNT_NUM_TEL_MOVIL, DCNT_EMAIL, DCNT_FECHA_REGISTR, CIDD_IDCIUDAD_ACTUAL, PAIS_IDPAIS_NACIONALIDAD, TPDC_IDTIPODOCUMENTO, CIDD_IDCIUDAD_EXP_DOC, INDEX, INDEX, INDEX, INDEX)
    VALUES (DCNT_IDDOCENTE, DCNT_APELLIDO1, DCNT_APELLIDO2, DCNT_NOMBRES, DCNT_NUM_LB_MILITAR, DCNT_FECHA_NAC, DCNT_DIRECCION_RESI, DCNT_NUM_TEL_FIJO, DCNT_NUM_TEL_MOVIL, DCNT_EMAIL, DCNT_FECHA_REGISTR, CIDD_IDCIUDAD_ACTUAL, PAIS_IDPAIS_NACIONALIDAD, TPDC_IDTIPODOCUMENTO, CIDD_IDCIUDAD_EXP_DOC, INDEX, INDEX, INDEX, INDEX);
END PR_INSERT_DOCENTE;
/

create or replace PROCEDURE PR_UPDATE_DOCENTE
(
    DCNT_IDDOCENTE NUMBER, DCNT_APELLIDO1 VARCHAR2, DCNT_APELLIDO2 VARCHAR2, DCNT_NOMBRES VARCHAR2, DCNT_NUM_LB_MILITAR VARCHAR2, DCNT_FECHA_NAC DATE, DCNT_DIRECCION_RESI VARCHAR2, DCNT_NUM_TEL_FIJO VARCHAR2, DCNT_NUM_TEL_MOVIL VARCHAR2, DCNT_EMAIL VARCHAR2, DCNT_FECHA_REGISTR DATE, CIDD_IDCIUDAD_ACTUAL NUMBER, PAIS_IDPAIS_NACIONALIDAD NUMBER, TPDC_IDTIPODOCUMENTO NUMBER, CIDD_IDCIUDAD_EXP_DOC NUMBER, INDEX `fk_docente_ciudad1_idx`, INDEX `fk_docente_pais1_idx`, INDEX `fk_docente_tipodocumento1_idx`, INDEX `fk_docente_ciudad2_idx`
)
AS BEGIN
    UPDATE SEMILLEROS_UDLA.DOCENTE O 
    SET O.DCNT_APELLIDO1 = DCNT_APELLIDO1, O.DCNT_APELLIDO2 = DCNT_APELLIDO2, O.DCNT_NOMBRES = DCNT_NOMBRES, O.DCNT_NUM_LB_MILITAR = DCNT_NUM_LB_MILITAR, O.DCNT_FECHA_NAC = DCNT_FECHA_NAC, O.DCNT_DIRECCION_RESI = DCNT_DIRECCION_RESI, O.DCNT_NUM_TEL_FIJO = DCNT_NUM_TEL_FIJO, O.DCNT_NUM_TEL_MOVIL = DCNT_NUM_TEL_MOVIL, O.DCNT_EMAIL = DCNT_EMAIL, O.DCNT_FECHA_REGISTR = DCNT_FECHA_REGISTR, O.CIDD_IDCIUDAD_ACTUAL = CIDD_IDCIUDAD_ACTUAL, O.PAIS_IDPAIS_NACIONALIDAD = PAIS_IDPAIS_NACIONALIDAD, O.TPDC_IDTIPODOCUMENTO = TPDC_IDTIPODOCUMENTO, O.CIDD_IDCIUDAD_EXP_DOC = CIDD_IDCIUDAD_EXP_DOC, O.INDEX = INDEX, O.INDEX = INDEX, O.INDEX = INDEX, O.INDEX = INDEX WHERE O.DCNT_IDDOCENTE = DCNT_IDDOCENTE;
END PR_UPDATE_DOCENTE;
/

create or replace PROCEDURE PR_SELECT_INSCRIPCION (CR_RESULT OUT SYS_REFCURSOR) AS
BEGIN
OPEN CR_RESULT FOR
    SELECT * FROM SEMILLEROS_UDLA.INSCRIPCION;
END PR_SELECT_INSCRIPCION;
/

create or replace PROCEDURE PR_INSERT_INSCRIPCION
(
    INCN_IDINSCRIPCION NUMBER, DCNT_IDDOCENTE NUMBER, INCN_MANIFESTACION VARCHAR2, INCN_DESDE DATE, INCN_HASTA DATE, INCN_LUGAR VARCHAR2, INCN_DESCRIPCION VARCHAR2, INCN_ATENCION1 DATE, INCN_ATENCION2 DATE, INDEX `fk_inscripcion_docente1_idx`
)
AS BEGIN
    INSERT INTO SEMILLEROS_UDLA.INSCRIPCION (INCN_IDINSCRIPCION, DCNT_IDDOCENTE, INCN_MANIFESTACION, INCN_DESDE, INCN_HASTA, INCN_LUGAR, INCN_DESCRIPCION, INCN_ATENCION1, INCN_ATENCION2, INDEX)
    VALUES (INCN_IDINSCRIPCION, DCNT_IDDOCENTE, INCN_MANIFESTACION, INCN_DESDE, INCN_HASTA, INCN_LUGAR, INCN_DESCRIPCION, INCN_ATENCION1, INCN_ATENCION2, INDEX);
END PR_INSERT_INSCRIPCION;
/

create or replace PROCEDURE PR_UPDATE_INSCRIPCION
(
    INCN_IDINSCRIPCION NUMBER, DCNT_IDDOCENTE NUMBER, INCN_MANIFESTACION VARCHAR2, INCN_DESDE DATE, INCN_HASTA DATE, INCN_LUGAR VARCHAR2, INCN_DESCRIPCION VARCHAR2, INCN_ATENCION1 DATE, INCN_ATENCION2 DATE, INDEX `fk_inscripcion_docente1_idx`
)
AS BEGIN
    UPDATE SEMILLEROS_UDLA.INSCRIPCION O 
    SET O.DCNT_IDDOCENTE = DCNT_IDDOCENTE, O.INCN_MANIFESTACION = INCN_MANIFESTACION, O.INCN_DESDE = INCN_DESDE, O.INCN_HASTA = INCN_HASTA, O.INCN_LUGAR = INCN_LUGAR, O.INCN_DESCRIPCION = INCN_DESCRIPCION, O.INCN_ATENCION1 = INCN_ATENCION1, O.INCN_ATENCION2 = INCN_ATENCION2, O.INDEX = INDEX WHERE O.INCN_IDINSCRIPCION = INCN_IDINSCRIPCION;
END PR_UPDATE_INSCRIPCION;
/

create or replace PROCEDURE PR_SELECT_ARCHIVO (CR_RESULT OUT SYS_REFCURSOR) AS
BEGIN
OPEN CR_RESULT FOR
    SELECT * FROM SEMILLEROS_UDLA.ARCHIVO;
END PR_SELECT_ARCHIVO;
/

create or replace PROCEDURE PR_INSERT_ARCHIVO
(
    ARCV_IDARCHIVO NUMBER, ARCV_DESCRIPCION VARCHAR2, ARCV_DIRNAME VARCHAR2
)
AS BEGIN
    INSERT INTO SEMILLEROS_UDLA.ARCHIVO (ARCV_IDARCHIVO, ARCV_DESCRIPCION, ARCV_DIRNAME)
    VALUES (ARCV_IDARCHIVO, ARCV_DESCRIPCION, ARCV_DIRNAME);
END PR_INSERT_ARCHIVO;
/

create or replace PROCEDURE PR_UPDATE_ARCHIVO
(
    ARCV_IDARCHIVO NUMBER, ARCV_DESCRIPCION VARCHAR2, ARCV_DIRNAME VARCHAR2
)
AS BEGIN
    UPDATE SEMILLEROS_UDLA.ARCHIVO O 
    SET O.ARCV_DESCRIPCION = ARCV_DESCRIPCION, O.ARCV_DIRNAME = ARCV_DIRNAME WHERE O.ARCV_IDARCHIVO = ARCV_IDARCHIVO;
END PR_UPDATE_ARCHIVO;
/

create or replace PROCEDURE PR_SELECT_TIPO_PROFESION (CR_RESULT OUT SYS_REFCURSOR) AS
BEGIN
OPEN CR_RESULT FOR
    SELECT * FROM SEMILLEROS_UDLA.TIPO_PROFESION;
END PR_SELECT_TIPO_PROFESION;
/

create or replace PROCEDURE PR_INSERT_TIPO_PROFESION
(
    TPPR_IDTIPOPROFESION NUMBER, TPPR_NOMBRE VARCHAR2,  ingenieria,  .....'
)
AS BEGIN
    INSERT INTO SEMILLEROS_UDLA.TIPO_PROFESION (TPPR_IDTIPOPROFESION, TPPR_NOMBRE, , )
    VALUES (TPPR_IDTIPOPROFESION, TPPR_NOMBRE, , );
END PR_INSERT_TIPO_PROFESION;
/

create or replace PROCEDURE PR_UPDATE_TIPO_PROFESION
(
    TPPR_IDTIPOPROFESION NUMBER, TPPR_NOMBRE VARCHAR2,  ingenieria,  .....'
)
AS BEGIN
    UPDATE SEMILLEROS_UDLA.TIPO_PROFESION O 
    SET O.TPPR_NOMBRE = TPPR_NOMBRE, O. = , O. =  WHERE O.TPPR_IDTIPOPROFESION = TPPR_IDTIPOPROFESION;
END PR_UPDATE_TIPO_PROFESION;
/

create or replace PROCEDURE PR_SELECT_PROFESION (CR_RESULT OUT SYS_REFCURSOR) AS
BEGIN
OPEN CR_RESULT FOR
    SELECT * FROM SEMILLEROS_UDLA.PROFESION;
END PR_SELECT_PROFESION;
/

create or replace PROCEDURE PR_INSERT_PROFESION
(
    PRFN_IDPROFESION NUMBER, PRFN_TITULO VARCHAR2, TPPR_IDTIPOPROFESION NUMBER, INDEX `fk_profesion_tipoprofesion1_idx`
)
AS BEGIN
    INSERT INTO SEMILLEROS_UDLA.PROFESION (PRFN_IDPROFESION, PRFN_TITULO, TPPR_IDTIPOPROFESION, INDEX)
    VALUES (PRFN_IDPROFESION, PRFN_TITULO, TPPR_IDTIPOPROFESION, INDEX);
END PR_INSERT_PROFESION;
/

create or replace PROCEDURE PR_UPDATE_PROFESION
(
    PRFN_IDPROFESION NUMBER, PRFN_TITULO VARCHAR2, TPPR_IDTIPOPROFESION NUMBER, INDEX `fk_profesion_tipoprofesion1_idx`
)
AS BEGIN
    UPDATE SEMILLEROS_UDLA.PROFESION O 
    SET O.PRFN_TITULO = PRFN_TITULO, O.TPPR_IDTIPOPROFESION = TPPR_IDTIPOPROFESION, O.INDEX = INDEX WHERE O.PRFN_IDPROFESION = PRFN_IDPROFESION;
END PR_UPDATE_PROFESION;
/

create or replace PROCEDURE PR_SELECT_PERFIL (CR_RESULT OUT SYS_REFCURSOR) AS
BEGIN
OPEN CR_RESULT FOR
    SELECT * FROM SEMILLEROS_UDLA.PERFIL;
END PR_SELECT_PERFIL;
/

create or replace PROCEDURE PR_INSERT_PERFIL
(
    PRFL_IDPERFIL NUMBER, PRFN_IDPROFESION NUMBER, DCNT_IDDOCENTE NUMBER, INDEX `fk_perfil_profesion1_idx`, INDEX `fk_perfil_docente1_idx`
)
AS BEGIN
    INSERT INTO SEMILLEROS_UDLA.PERFIL (PRFL_IDPERFIL, PRFN_IDPROFESION, DCNT_IDDOCENTE, INDEX, INDEX)
    VALUES (PRFL_IDPERFIL, PRFN_IDPROFESION, DCNT_IDDOCENTE, INDEX, INDEX);
END PR_INSERT_PERFIL;
/

create or replace PROCEDURE PR_UPDATE_PERFIL
(
    PRFL_IDPERFIL NUMBER, PRFN_IDPROFESION NUMBER, DCNT_IDDOCENTE NUMBER, INDEX `fk_perfil_profesion1_idx`, INDEX `fk_perfil_docente1_idx`
)
AS BEGIN
    UPDATE SEMILLEROS_UDLA.PERFIL O 
    SET O.PRFN_IDPROFESION = PRFN_IDPROFESION, O.DCNT_IDDOCENTE = DCNT_IDDOCENTE, O.INDEX = INDEX, O.INDEX = INDEX WHERE O.PRFL_IDPERFIL = PRFL_IDPERFIL;
END PR_UPDATE_PERFIL;
/

create or replace PROCEDURE PR_SELECT_SOPORTE (CR_RESULT OUT SYS_REFCURSOR) AS
BEGIN
OPEN CR_RESULT FOR
    SELECT * FROM SEMILLEROS_UDLA.SOPORTE;
END PR_SELECT_SOPORTE;
/

create or replace PROCEDURE PR_INSERT_SOPORTE
(
    SPTE_FECHAREGISTRO DATE, ARCV_IDARCHIVO NUMBER, DCNT_IDDOCENTE NUMBER, INDEX `fk_soporte_docente1_idx`
)
AS BEGIN
    INSERT INTO SEMILLEROS_UDLA.SOPORTE (SPTE_FECHAREGISTRO, ARCV_IDARCHIVO, DCNT_IDDOCENTE, INDEX)
    VALUES (SPTE_FECHAREGISTRO, ARCV_IDARCHIVO, DCNT_IDDOCENTE, INDEX);
END PR_INSERT_SOPORTE;
/

create or replace PROCEDURE PR_UPDATE_SOPORTE
(
    SPTE_FECHAREGISTRO DATE, ARCV_IDARCHIVO NUMBER, DCNT_IDDOCENTE NUMBER, INDEX `fk_soporte_docente1_idx`
)
AS BEGIN
    UPDATE SEMILLEROS_UDLA.SOPORTE O 
    SET O.ARCV_IDARCHIVO = ARCV_IDARCHIVO, O.DCNT_IDDOCENTE = DCNT_IDDOCENTE, O.INDEX = INDEX WHERE O.SPTE_FECHAREGISTRO = SPTE_FECHAREGISTRO;
END PR_UPDATE_SOPORTE;
/

create or replace PROCEDURE PR_SELECT_PERSONAL (CR_RESULT OUT SYS_REFCURSOR) AS
BEGIN
OPEN CR_RESULT FOR
    SELECT * FROM SEMILLEROS_UDLA.PERSONAL;
END PR_SELECT_PERSONAL;
/

create or replace PROCEDURE PR_INSERT_PERSONAL
(
    PRSL_IDPERSONAL NUMBER, PRSL_PUNTAJE_TOTAL NUMBER, PRSL_PUNTAJE_MAX NUMBER
)
AS BEGIN
    INSERT INTO SEMILLEROS_UDLA.PERSONAL (PRSL_IDPERSONAL, PRSL_PUNTAJE_TOTAL, PRSL_PUNTAJE_MAX)
    VALUES (PRSL_IDPERSONAL, PRSL_PUNTAJE_TOTAL, PRSL_PUNTAJE_MAX);
END PR_INSERT_PERSONAL;
/

create or replace PROCEDURE PR_UPDATE_PERSONAL
(
    PRSL_IDPERSONAL NUMBER, PRSL_PUNTAJE_TOTAL NUMBER, PRSL_PUNTAJE_MAX NUMBER
)
AS BEGIN
    UPDATE SEMILLEROS_UDLA.PERSONAL O 
    SET O.PRSL_PUNTAJE_TOTAL = PRSL_PUNTAJE_TOTAL, O.PRSL_PUNTAJE_MAX = PRSL_PUNTAJE_MAX WHERE O.PRSL_IDPERSONAL = PRSL_IDPERSONAL;
END PR_UPDATE_PERSONAL;
/

create or replace PROCEDURE PR_SELECT_INVESTIGACION (CR_RESULT OUT SYS_REFCURSOR) AS
BEGIN
OPEN CR_RESULT FOR
    SELECT * FROM SEMILLEROS_UDLA.INVESTIGACION;
END PR_SELECT_INVESTIGACION;
/

create or replace PROCEDURE PR_INSERT_INVESTIGACION
(
    INVN_IDINVESTIGACION NUMBER, INVN_PUNTAJE_TOTAL NUMBER, INVN_PUNTAJE_MAX NUMBER
)
AS BEGIN
    INSERT INTO SEMILLEROS_UDLA.INVESTIGACION (INVN_IDINVESTIGACION, INVN_PUNTAJE_TOTAL, INVN_PUNTAJE_MAX)
    VALUES (INVN_IDINVESTIGACION, INVN_PUNTAJE_TOTAL, INVN_PUNTAJE_MAX);
END PR_INSERT_INVESTIGACION;
/

create or replace PROCEDURE PR_UPDATE_INVESTIGACION
(
    INVN_IDINVESTIGACION NUMBER, INVN_PUNTAJE_TOTAL NUMBER, INVN_PUNTAJE_MAX NUMBER
)
AS BEGIN
    UPDATE SEMILLEROS_UDLA.INVESTIGACION O 
    SET O.INVN_PUNTAJE_TOTAL = INVN_PUNTAJE_TOTAL, O.INVN_PUNTAJE_MAX = INVN_PUNTAJE_MAX WHERE O.INVN_IDINVESTIGACION = INVN_IDINVESTIGACION;
END PR_UPDATE_INVESTIGACION;
/

create or replace PROCEDURE PR_SELECT_DOCENCIA (CR_RESULT OUT SYS_REFCURSOR) AS
BEGIN
OPEN CR_RESULT FOR
    SELECT * FROM SEMILLEROS_UDLA.DOCENCIA;
END PR_SELECT_DOCENCIA;
/

create or replace PROCEDURE PR_INSERT_DOCENCIA
(
    DCCA_IDDOCENCIA NUMBER, DCCA_PUNTAJE_TOTAL NUMBER, DCCA_PUNTAJE_MAX NUMBER
)
AS BEGIN
    INSERT INTO SEMILLEROS_UDLA.DOCENCIA (DCCA_IDDOCENCIA, DCCA_PUNTAJE_TOTAL, DCCA_PUNTAJE_MAX)
    VALUES (DCCA_IDDOCENCIA, DCCA_PUNTAJE_TOTAL, DCCA_PUNTAJE_MAX);
END PR_INSERT_DOCENCIA;
/

create or replace PROCEDURE PR_UPDATE_DOCENCIA
(
    DCCA_IDDOCENCIA NUMBER, DCCA_PUNTAJE_TOTAL NUMBER, DCCA_PUNTAJE_MAX NUMBER
)
AS BEGIN
    UPDATE SEMILLEROS_UDLA.DOCENCIA O 
    SET O.DCCA_PUNTAJE_TOTAL = DCCA_PUNTAJE_TOTAL, O.DCCA_PUNTAJE_MAX = DCCA_PUNTAJE_MAX WHERE O.DCCA_IDDOCENCIA = DCCA_IDDOCENCIA;
END PR_UPDATE_DOCENCIA;
/

create or replace PROCEDURE PR_SELECT_PROFESIONAL (CR_RESULT OUT SYS_REFCURSOR) AS
BEGIN
OPEN CR_RESULT FOR
    SELECT * FROM SEMILLEROS_UDLA.PROFESIONAL;
END PR_SELECT_PROFESIONAL;
/

create or replace PROCEDURE PR_INSERT_PROFESIONAL
(
    PNAL_IDPROFESIONAL NUMBER, PNAL_PUNTAJE_TOTAL NUMBER, PNAL_PUNTAJE_MAX NUMBER
)
AS BEGIN
    INSERT INTO SEMILLEROS_UDLA.PROFESIONAL (PNAL_IDPROFESIONAL, PNAL_PUNTAJE_TOTAL, PNAL_PUNTAJE_MAX)
    VALUES (PNAL_IDPROFESIONAL, PNAL_PUNTAJE_TOTAL, PNAL_PUNTAJE_MAX);
END PR_INSERT_PROFESIONAL;
/

create or replace PROCEDURE PR_UPDATE_PROFESIONAL
(
    PNAL_IDPROFESIONAL NUMBER, PNAL_PUNTAJE_TOTAL NUMBER, PNAL_PUNTAJE_MAX NUMBER
)
AS BEGIN
    UPDATE SEMILLEROS_UDLA.PROFESIONAL O 
    SET O.PNAL_PUNTAJE_TOTAL = PNAL_PUNTAJE_TOTAL, O.PNAL_PUNTAJE_MAX = PNAL_PUNTAJE_MAX WHERE O.PNAL_IDPROFESIONAL = PNAL_IDPROFESIONAL;
END PR_UPDATE_PROFESIONAL;
/

create or replace PROCEDURE PR_SELECT_PRODUCCION (CR_RESULT OUT SYS_REFCURSOR) AS
BEGIN
OPEN CR_RESULT FOR
    SELECT * FROM SEMILLEROS_UDLA.PRODUCCION;
END PR_SELECT_PRODUCCION;
/

create or replace PROCEDURE PR_INSERT_PRODUCCION
(
    PRCN_IDPRODUCCION NUMBER, PRCN_PUNTAJE_TOTAL NUMBER, PRCN_PUNTAJE_MAX NUMBER
)
AS BEGIN
    INSERT INTO SEMILLEROS_UDLA.PRODUCCION (PRCN_IDPRODUCCION, PRCN_PUNTAJE_TOTAL, PRCN_PUNTAJE_MAX)
    VALUES (PRCN_IDPRODUCCION, PRCN_PUNTAJE_TOTAL, PRCN_PUNTAJE_MAX);
END PR_INSERT_PRODUCCION;
/

create or replace PROCEDURE PR_UPDATE_PRODUCCION
(
    PRCN_IDPRODUCCION NUMBER, PRCN_PUNTAJE_TOTAL NUMBER, PRCN_PUNTAJE_MAX NUMBER
)
AS BEGIN
    UPDATE SEMILLEROS_UDLA.PRODUCCION O 
    SET O.PRCN_PUNTAJE_TOTAL = PRCN_PUNTAJE_TOTAL, O.PRCN_PUNTAJE_MAX = PRCN_PUNTAJE_MAX WHERE O.PRCN_IDPRODUCCION = PRCN_IDPRODUCCION;
END PR_UPDATE_PRODUCCION;
/

create or replace PROCEDURE PR_SELECT_COMPETENCIA (CR_RESULT OUT SYS_REFCURSOR) AS
BEGIN
OPEN CR_RESULT FOR
    SELECT * FROM SEMILLEROS_UDLA.COMPETENCIA;
END PR_SELECT_COMPETENCIA;
/

create or replace PROCEDURE PR_INSERT_COMPETENCIA
(
    CMPC_IDCOMPETENCIA NUMBER, CMPC_PUNTAJE_TOTAL VARCHAR2, CMPC_MAX_PUNTOS NUMBER, PRSL_IDPERSONAL NUMBER, INVN_IDINVESTIGACION NUMBER, DCCA_IDDOCENCIA NUMBER, PNAL_IDPROFESIONAL NUMBER, PRCN_IDPRODUCCION NUMBER, INDEX `fk_competencia_personal1_idx`, INDEX `fk_competencia_investigacion1_idx`, INDEX `fk_competencia_docencia1_idx`, INDEX `fk_competencia_profesional1_idx`, INDEX `fk_competencia_produccion1_idx`
)
AS BEGIN
    INSERT INTO SEMILLEROS_UDLA.COMPETENCIA (CMPC_IDCOMPETENCIA, CMPC_PUNTAJE_TOTAL, CMPC_MAX_PUNTOS, PRSL_IDPERSONAL, INVN_IDINVESTIGACION, DCCA_IDDOCENCIA, PNAL_IDPROFESIONAL, PRCN_IDPRODUCCION, INDEX, INDEX, INDEX, INDEX, INDEX)
    VALUES (CMPC_IDCOMPETENCIA, CMPC_PUNTAJE_TOTAL, CMPC_MAX_PUNTOS, PRSL_IDPERSONAL, INVN_IDINVESTIGACION, DCCA_IDDOCENCIA, PNAL_IDPROFESIONAL, PRCN_IDPRODUCCION, INDEX, INDEX, INDEX, INDEX, INDEX);
END PR_INSERT_COMPETENCIA;
/

create or replace PROCEDURE PR_UPDATE_COMPETENCIA
(
    CMPC_IDCOMPETENCIA NUMBER, CMPC_PUNTAJE_TOTAL VARCHAR2, CMPC_MAX_PUNTOS NUMBER, PRSL_IDPERSONAL NUMBER, INVN_IDINVESTIGACION NUMBER, DCCA_IDDOCENCIA NUMBER, PNAL_IDPROFESIONAL NUMBER, PRCN_IDPRODUCCION NUMBER, INDEX `fk_competencia_personal1_idx`, INDEX `fk_competencia_investigacion1_idx`, INDEX `fk_competencia_docencia1_idx`, INDEX `fk_competencia_profesional1_idx`, INDEX `fk_competencia_produccion1_idx`
)
AS BEGIN
    UPDATE SEMILLEROS_UDLA.COMPETENCIA O 
    SET O.CMPC_PUNTAJE_TOTAL = CMPC_PUNTAJE_TOTAL, O.CMPC_MAX_PUNTOS = CMPC_MAX_PUNTOS, O.PRSL_IDPERSONAL = PRSL_IDPERSONAL, O.INVN_IDINVESTIGACION = INVN_IDINVESTIGACION, O.DCCA_IDDOCENCIA = DCCA_IDDOCENCIA, O.PNAL_IDPROFESIONAL = PNAL_IDPROFESIONAL, O.PRCN_IDPRODUCCION = PRCN_IDPRODUCCION, O.INDEX = INDEX, O.INDEX = INDEX, O.INDEX = INDEX, O.INDEX = INDEX, O.INDEX = INDEX WHERE O.CMPC_IDCOMPETENCIA = CMPC_IDCOMPETENCIA;
END PR_UPDATE_COMPETENCIA;
/

create or replace PROCEDURE PR_SELECT_PERSONAL_DETALLE (CR_RESULT OUT SYS_REFCURSOR) AS
BEGIN
OPEN CR_RESULT FOR
    SELECT * FROM SEMILLEROS_UDLA.PERSONAL_DETALLE;
END PR_SELECT_PERSONAL_DETALLE;
/

create or replace PROCEDURE PR_INSERT_PERSONAL_DETALLE
(
    TPPR_IDTIPOPROFESION NUMBER, PRDT_UNIVERSIDAD VARCHAR2, PRDT_GRADO DATE, PRDT_PUNTAJE NUMBER, PRDT_PUNTAJE_MAX NUMBER, PERSONAL_PRSL_IDPERSONAL NUMBER, INDEX `fk_personal_detalle_personal1_idx`
)
AS BEGIN
    INSERT INTO SEMILLEROS_UDLA.PERSONAL_DETALLE (TPPR_IDTIPOPROFESION, PRDT_UNIVERSIDAD, PRDT_GRADO, PRDT_PUNTAJE, PRDT_PUNTAJE_MAX, PERSONAL_PRSL_IDPERSONAL, INDEX)
    VALUES (TPPR_IDTIPOPROFESION, PRDT_UNIVERSIDAD, PRDT_GRADO, PRDT_PUNTAJE, PRDT_PUNTAJE_MAX, PERSONAL_PRSL_IDPERSONAL, INDEX);
END PR_INSERT_PERSONAL_DETALLE;
/

create or replace PROCEDURE PR_UPDATE_PERSONAL_DETALLE
(
    TPPR_IDTIPOPROFESION NUMBER, PRDT_UNIVERSIDAD VARCHAR2, PRDT_GRADO DATE, PRDT_PUNTAJE NUMBER, PRDT_PUNTAJE_MAX NUMBER, PERSONAL_PRSL_IDPERSONAL NUMBER, INDEX `fk_personal_detalle_personal1_idx`
)
AS BEGIN
    UPDATE SEMILLEROS_UDLA.PERSONAL_DETALLE O 
    SET O.PRDT_UNIVERSIDAD = PRDT_UNIVERSIDAD, O.PRDT_GRADO = PRDT_GRADO, O.PRDT_PUNTAJE = PRDT_PUNTAJE, O.PRDT_PUNTAJE_MAX = PRDT_PUNTAJE_MAX, O.PERSONAL_PRSL_IDPERSONAL = PERSONAL_PRSL_IDPERSONAL, O.INDEX = INDEX WHERE O.TPPR_IDTIPOPROFESION = TPPR_IDTIPOPROFESION;
END PR_UPDATE_PERSONAL_DETALLE;
/

create or replace PROCEDURE PR_SELECT_INVESTIGACION_DETALLE (CR_RESULT OUT SYS_REFCURSOR) AS
BEGIN
OPEN CR_RESULT FOR
    SELECT * FROM SEMILLEROS_UDLA.INVESTIGACION_DETALLE;
END PR_SELECT_INVESTIGACION_DETALLE;
/

create or replace PROCEDURE PR_INSERT_INVESTIGACION_DETALLE
(
    INVD_IDINVESTIGACION_DETALLE NUMBER, INVD_FINANCIADORA VARCHAR2, INVD_FECHA_INICIO DATE, INVD_FECHA_FIN DATE, INVD_PUNTAJE NUMBER, INVN_IDINVESTIGACION NUMBER, INDEX `fk_investigacion_detalle_investigacion1_idx`
)
AS BEGIN
    INSERT INTO SEMILLEROS_UDLA.INVESTIGACION_DETALLE (INVD_IDINVESTIGACION_DETALLE, INVD_FINANCIADORA, INVD_FECHA_INICIO, INVD_FECHA_FIN, INVD_PUNTAJE, INVN_IDINVESTIGACION, INDEX)
    VALUES (INVD_IDINVESTIGACION_DETALLE, INVD_FINANCIADORA, INVD_FECHA_INICIO, INVD_FECHA_FIN, INVD_PUNTAJE, INVN_IDINVESTIGACION, INDEX);
END PR_INSERT_INVESTIGACION_DETALLE;
/

create or replace PROCEDURE PR_UPDATE_INVESTIGACION_DETALLE
(
    INVD_IDINVESTIGACION_DETALLE NUMBER, INVD_FINANCIADORA VARCHAR2, INVD_FECHA_INICIO DATE, INVD_FECHA_FIN DATE, INVD_PUNTAJE NUMBER, INVN_IDINVESTIGACION NUMBER, INDEX `fk_investigacion_detalle_investigacion1_idx`
)
AS BEGIN
    UPDATE SEMILLEROS_UDLA.INVESTIGACION_DETALLE O 
    SET O.INVD_FINANCIADORA = INVD_FINANCIADORA, O.INVD_FECHA_INICIO = INVD_FECHA_INICIO, O.INVD_FECHA_FIN = INVD_FECHA_FIN, O.INVD_PUNTAJE = INVD_PUNTAJE, O.INVN_IDINVESTIGACION = INVN_IDINVESTIGACION, O.INDEX = INDEX WHERE O.INVD_IDINVESTIGACION_DETALLE = INVD_IDINVESTIGACION_DETALLE;
END PR_UPDATE_INVESTIGACION_DETALLE;
/

create or replace PROCEDURE PR_SELECT_DOCENCIA_DETALLE (CR_RESULT OUT SYS_REFCURSOR) AS
BEGIN
OPEN CR_RESULT FOR
    SELECT * FROM SEMILLEROS_UDLA.DOCENCIA_DETALLE;
END PR_SELECT_DOCENCIA_DETALLE;
/

create or replace PROCEDURE PR_INSERT_DOCENCIA_DETALLE
(
    DCDT_IDDOCENCIA_DETALLE NUMBER, DCDT_INSTITUCION VARCHAR2, DCDT_AREA_TRABAJO VARCHAR2, DCDT_CARGO VARCHAR2, DCDT_INICIO DATE, DCDT_FIN DATE, DCDT_PUNTAJE VARCHAR2, DCCA_IDDOCENCIA NUMBER, INDEX `fk_docencia_detalle_docencia1_idx`
)
AS BEGIN
    INSERT INTO SEMILLEROS_UDLA.DOCENCIA_DETALLE (DCDT_IDDOCENCIA_DETALLE, DCDT_INSTITUCION, DCDT_AREA_TRABAJO, DCDT_CARGO, DCDT_INICIO, DCDT_FIN, DCDT_PUNTAJE, DCCA_IDDOCENCIA, INDEX)
    VALUES (DCDT_IDDOCENCIA_DETALLE, DCDT_INSTITUCION, DCDT_AREA_TRABAJO, DCDT_CARGO, DCDT_INICIO, DCDT_FIN, DCDT_PUNTAJE, DCCA_IDDOCENCIA, INDEX);
END PR_INSERT_DOCENCIA_DETALLE;
/

create or replace PROCEDURE PR_UPDATE_DOCENCIA_DETALLE
(
    DCDT_IDDOCENCIA_DETALLE NUMBER, DCDT_INSTITUCION VARCHAR2, DCDT_AREA_TRABAJO VARCHAR2, DCDT_CARGO VARCHAR2, DCDT_INICIO DATE, DCDT_FIN DATE, DCDT_PUNTAJE VARCHAR2, DCCA_IDDOCENCIA NUMBER, INDEX `fk_docencia_detalle_docencia1_idx`
)
AS BEGIN
    UPDATE SEMILLEROS_UDLA.DOCENCIA_DETALLE O 
    SET O.DCDT_INSTITUCION = DCDT_INSTITUCION, O.DCDT_AREA_TRABAJO = DCDT_AREA_TRABAJO, O.DCDT_CARGO = DCDT_CARGO, O.DCDT_INICIO = DCDT_INICIO, O.DCDT_FIN = DCDT_FIN, O.DCDT_PUNTAJE = DCDT_PUNTAJE, O.DCCA_IDDOCENCIA = DCCA_IDDOCENCIA, O.INDEX = INDEX WHERE O.DCDT_IDDOCENCIA_DETALLE = DCDT_IDDOCENCIA_DETALLE;
END PR_UPDATE_DOCENCIA_DETALLE;
/

create or replace PROCEDURE PR_SELECT_PROFESIONAL_DETALLE (CR_RESULT OUT SYS_REFCURSOR) AS
BEGIN
OPEN CR_RESULT FOR
    SELECT * FROM SEMILLEROS_UDLA.PROFESIONAL_DETALLE;
END PR_SELECT_PROFESIONAL_DETALLE;
/

create or replace PROCEDURE PR_INSERT_PROFESIONAL_DETALLE
(
    PFDT_IDPROFESIONAL_DETALLE NUMBER, PFDT_INSTITUCION VARCHAR2, PFDT_AREA_TRABAJO VARCHAR2, PFDT_CARGO VARCHAR2, PFDT_FIN DATE, PFDT_INICIO DATE, PFDT_PUNTAJE NUMBER, PNAL_IDPROFESIONAL NUMBER, INDEX `fk_profesional_detalle_profesional1_idx`
)
AS BEGIN
    INSERT INTO SEMILLEROS_UDLA.PROFESIONAL_DETALLE (PFDT_IDPROFESIONAL_DETALLE, PFDT_INSTITUCION, PFDT_AREA_TRABAJO, PFDT_CARGO, PFDT_FIN, PFDT_INICIO, PFDT_PUNTAJE, PNAL_IDPROFESIONAL, INDEX)
    VALUES (PFDT_IDPROFESIONAL_DETALLE, PFDT_INSTITUCION, PFDT_AREA_TRABAJO, PFDT_CARGO, PFDT_FIN, PFDT_INICIO, PFDT_PUNTAJE, PNAL_IDPROFESIONAL, INDEX);
END PR_INSERT_PROFESIONAL_DETALLE;
/

create or replace PROCEDURE PR_UPDATE_PROFESIONAL_DETALLE
(
    PFDT_IDPROFESIONAL_DETALLE NUMBER, PFDT_INSTITUCION VARCHAR2, PFDT_AREA_TRABAJO VARCHAR2, PFDT_CARGO VARCHAR2, PFDT_FIN DATE, PFDT_INICIO DATE, PFDT_PUNTAJE NUMBER, PNAL_IDPROFESIONAL NUMBER, INDEX `fk_profesional_detalle_profesional1_idx`
)
AS BEGIN
    UPDATE SEMILLEROS_UDLA.PROFESIONAL_DETALLE O 
    SET O.PFDT_INSTITUCION = PFDT_INSTITUCION, O.PFDT_AREA_TRABAJO = PFDT_AREA_TRABAJO, O.PFDT_CARGO = PFDT_CARGO, O.PFDT_FIN = PFDT_FIN, O.PFDT_INICIO = PFDT_INICIO, O.PFDT_PUNTAJE = PFDT_PUNTAJE, O.PNAL_IDPROFESIONAL = PNAL_IDPROFESIONAL, O.INDEX = INDEX WHERE O.PFDT_IDPROFESIONAL_DETALLE = PFDT_IDPROFESIONAL_DETALLE;
END PR_UPDATE_PROFESIONAL_DETALLE;
/

create or replace PROCEDURE PR_SELECT_PRODUCCION_DETALLE (CR_RESULT OUT SYS_REFCURSOR) AS
BEGIN
OPEN CR_RESULT FOR
    SELECT * FROM SEMILLEROS_UDLA.PRODUCCION_DETALLE;
END PR_SELECT_PRODUCCION_DETALLE;
/

create or replace PROCEDURE PR_INSERT_PRODUCCION_DETALLE
(
    PNDT_IDPRODUCCION NUMBER, PNDT_NOMBRE_PRODUCTO VARCHAR2, PNDT_TIPO_PRODUCTO VARCHAR2, PNDT_IDENTIFICADOR_CERT VARCHAR2, PNDT_VOLUMEN VARCHAR2, PNDT_FECHA_EDICION DATE, PNDT_PUNTAJE NUMBER, PRCN_IDPRODUCCION NUMBER, INDEX `fk_produccion_detalle_produccion1_idx`
)
AS BEGIN
    INSERT INTO SEMILLEROS_UDLA.PRODUCCION_DETALLE (PNDT_IDPRODUCCION, PNDT_NOMBRE_PRODUCTO, PNDT_TIPO_PRODUCTO, PNDT_IDENTIFICADOR_CERT, PNDT_VOLUMEN, PNDT_FECHA_EDICION, PNDT_PUNTAJE, PRCN_IDPRODUCCION, INDEX)
    VALUES (PNDT_IDPRODUCCION, PNDT_NOMBRE_PRODUCTO, PNDT_TIPO_PRODUCTO, PNDT_IDENTIFICADOR_CERT, PNDT_VOLUMEN, PNDT_FECHA_EDICION, PNDT_PUNTAJE, PRCN_IDPRODUCCION, INDEX);
END PR_INSERT_PRODUCCION_DETALLE;
/

create or replace PROCEDURE PR_UPDATE_PRODUCCION_DETALLE
(
    PNDT_IDPRODUCCION NUMBER, PNDT_NOMBRE_PRODUCTO VARCHAR2, PNDT_TIPO_PRODUCTO VARCHAR2, PNDT_IDENTIFICADOR_CERT VARCHAR2, PNDT_VOLUMEN VARCHAR2, PNDT_FECHA_EDICION DATE, PNDT_PUNTAJE NUMBER, PRCN_IDPRODUCCION NUMBER, INDEX `fk_produccion_detalle_produccion1_idx`
)
AS BEGIN
    UPDATE SEMILLEROS_UDLA.PRODUCCION_DETALLE O 
    SET O.PNDT_NOMBRE_PRODUCTO = PNDT_NOMBRE_PRODUCTO, O.PNDT_TIPO_PRODUCTO = PNDT_TIPO_PRODUCTO, O.PNDT_IDENTIFICADOR_CERT = PNDT_IDENTIFICADOR_CERT, O.PNDT_VOLUMEN = PNDT_VOLUMEN, O.PNDT_FECHA_EDICION = PNDT_FECHA_EDICION, O.PNDT_PUNTAJE = PNDT_PUNTAJE, O.PRCN_IDPRODUCCION = PRCN_IDPRODUCCION, O.INDEX = INDEX WHERE O.PNDT_IDPRODUCCION = PNDT_IDPRODUCCION;
END PR_UPDATE_PRODUCCION_DETALLE;
/

